[package]
name = "ai_dventure"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
colored = "2.0"
clap = { version = "4.5.45", features = ["derive", "env"] }
textwrap = "0.16"
